[package]
name = "awk"
version = "0.1.0"
authors = ["wirelyre <wirelyre@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
failure = "0.1.5"
itertools = "0.8.0"
lazy_static = "1.3"
pest = "2.1"
pest_derive = "2.1"
rand = "0.6.5"
regex = "1.0"
